### ISSUE TITLE
Error with project

### ISSUE THREAD

**Issue by janetrbarclay** [usgs/sfrmaker#104]
When I call functions from sfrmaker that utilize project from gisutils, I'm getting an error that the project 'module' object is not callable. In the gisutils files, it looks like project is superseded by projection. Does this need to updated in the sfrmaker files? When I change the sfrmaker import statements to import projection instead of project and change the call to project to projection.project, my script runs without error, though I have not yet inspected the results.

**Comment by aleaf** [comment]
Hi @janetrbarclay, what versions of SFRmaker and gis-utils are you running? If they aren't the latest (sfrmaker 0.7.0 and gis-utils 0.2.6), I'd recommend updating (e.g. ``pip install --upgrade sfrmaker``). If you are still getting the error(s), can you provide a short reproducible code example? Thanks

**Comment by janetrbarclay** [comment]
Hi @aleaf, I have the latest versions of sfrmaker and gis-utils. 

**Here's some code I was running:** (shapefile is attached in case that's helpful)
[clip_box.zip](https://github.com/aleaf/sfrmaker/files/5842672/clip_box.zip)


import numpy as np
import matplotlib.pyplot as plt
import flopy
import sfrmaker

NHDPlus_paths = r'C:\Workspace\gw-general-models\Genmod1.0\input_data\NHDPlusV2Data\NHDPlusNE\NHDPlus01'

lns = sfrmaker.Lines.from_nhdplus_v2(NHDPlus_paths=NHDPlus_paths,  filter=r'C:\Workspace\gw-general-models\Genmod1.0\subprojects\siteGeneral\Niantic\clip_box.shp')



**And here's the text of the error:**
loading NHDPlus v2 hydrography data...
for basins:
C:\Workspace\gw-general-models\Genmod1.0\input_data\NHDPlusV2Data\NHDPlusNE\NHDPlus01
Traceback (most recent call last):
  File "C:/Users/jbarclay/OneDrive - DOI/LISS/Analysis/Python/SFR_maker_test_2.py", line 11, in <module>
    filter=r'C:\Workspace\gw-general-models\Genmod1.0\subprojects\siteGeneral\Niantic\clip_box.shp')
  File "C:\Users\jbarclay\.conda\envs\sfrmaker\lib\site-packages\sfrmaker\lines.py", line 600, in from_nhdplus_v2
    epsg=epsg, proj_str=proj_str, prjfile=prjfile)
  File "C:\Users\jbarclay\.conda\envs\sfrmaker\lib\site-packages\sfrmaker\nhdplus_utils.py", line 122, in load_nhdplus_v2
    filter = get_bbox(filter, dest_crs=nhdcrs)
  File "C:\Users\jbarclay\.conda\envs\sfrmaker\lib\site-packages\sfrmaker\gis.py", line 260, in get_bbox
    bbox_dest_crs = project(bbox_src_crs, shpcrs, dest_crs)
TypeError: 'module' object is not callable


If I remove the filter, Lines.from_nhdplus_v2 runs without error, but then I get the same error when I run Lines.to_sfr except it is in "sfrmaker\lines.py", line 324, in to_crs
    geoms = project(self.df.geometry, self.crs, dest_crs)

**Comment by aleaf** [comment]
Hi @janetrbarclay just to be clear, when you run this code in a python interpreter (within the environment that you are using with sfrmaker), what version to you get?
```python
import gisutils
gisutils.__version__
```
Similarly, at the Anaconda prompt with the appropriate environment activated, when you run ``conda list`` what does it report for gis-utils and sfrmaker? Thanks

**Comment by janetrbarclay** [comment]
Hi @aleaf , thanks for your help. 
At the python prompt, I get:
>>> import gisutils
>>> gisutils.__version__
'0.2.6'
>>> import sfrmaker
>>> sfrmaker.__version__
'0.7.0'

and from conda list I get:
![image](https://user-images.githubusercontent.com/3833808/105190959-90aa2a80-5b04-11eb-86e1-f8ca845b5166.png)

**Comment by aleaf** [comment]
Hi @janetrbarclay, I can't reproduce this error- on OSX or Windows. 

Based on the error message, it seems most likely that somehow, an outdated version of [gis-utils](https://github.com/aleaf/gis-utils) is being imported. With commit 683863d42 to gis-utils, the `project.py` module was renamed to `projection.py`, to avoid confusion with the `project` function that is also in the top-level namespace for gis-utils (e.g. so that one can import the function with `from gisutils import project`). Since that commit, gis-utils should warn users on import of `project` that the module `project` has been renamed. It doesn't look like you are getting this warning, and the error message suggests that `project` for you is a module (not a function). 

So, I would suggest [creating a new conda environment](https://aleaf.github.io/sfrmaker/latest/installation.html#creating-a-conda-environment) with `requirements.yml` or `gis.yml` (if you want more packages, including the ability to run jupyter notebooks). And then [install sfrmaker](https://aleaf.github.io/sfrmaker/latest/installation.html) and try your script in the new environment.

**Comment by janetrbarclay** [comment]
@aleaf sounds good. I'll do that and let you know how it turns out. Thanks!

**Comment by janetrbarclay** [comment]
HI @aleaf - recreating the environment seems to have fixed the issue. Thanks for your help.
